services:
  ssh:
    image: rastasheep/ubuntu-sshd:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_USERNAME: Agent_Smith
        SSH_PASSWORD: tinkerbell
    ports:
      - "22:22"
    volumes:
      - ./shared:/home/Agent_Smith