services:
  ftp:
    image: garethflowers/ftp-server
    environment:
      - FTP_USER=hello
      - FTP_PASS=access
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp' 
    volumes:
      - ./shared:/home/hello
    command: >
      sh -c "echo 'Only user \"hello\" is allowed to access this FTP server.' > /etc/vsftpd.banner &&
             echo 'banner_file=/etc/vsftpd.banner' >> /etc/vsftpd.conf &&
             /usr/sbin/vsftpd /etc/vsftpd.conf"
    runtime: runsc
      